[package]
name = "useful-serenity"
version = "0.1.2"
description = "Useful Serenity tools"
repository = "https://github.com/misilelab/UsefulSerenity"
documentation = "https://docs.rs/UsefulSerenity"
authors = ["MisileLaboratory"]
readme = "README.md"
license-file = "LICENSE.md"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = { version = "0.10", default-features = false, features = ["client", "gateway", "model", "rustls_backend", "unstable_discord_api"] }
tokio = { version = "1.17.0", features = ["full"] }
